server:
  port: ${PORT:8080}

spring:
  application:
    name: proyectofinal
  datasource:
    # Agregamos los valores por defecto después de los dos puntos (:)
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:academic_events_db}
    username: ${DB_USERNAME:ups}
    password: ${DB_PASSWORD:secret}
    hikari:
      maximum-pool-size: 5
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  data:
    redis:
      # Valores por defecto para Redis también
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:TuClaveSuperSecretaGeneradaEnBase64QueTengaAlMenos256BitsDeLongitudParaEvitarErrores}
  access-expiration: ${JWT_ACCESS_EXPIRATION:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:8080}

swagger:
  security:
    enabled: ${SWAGGER_SECURITY_ENABLED:true}
    username: ${SWAGGER_USERNAME:evaluator}
    password: ${SWAGGER_PASSWORD:evaluator123}

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "never"