-- ============================================================================
-- Proyecto Integrador: API REST segura para gestión de eventos académicos
-- Motor: PostgreSQL 15+
-- Migración Flyway: V1__initial_schema_and_data.sql
--
-- La base de datos debe existir antes de ejecutar esta migración.
-- Nombre sugerido: academic_events_db
--
-- Credenciales de prueba para todos los usuarios insertados:
-- Contraseña: Password123*
-- Hash BCrypt: $2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe
-- ============================================================================

-- --------------------------------------------------------------------------
-- Función común para mantener automáticamente updated_at.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- --------------------------------------------------------------------------
-- 1. ROLES
-- --------------------------------------------------------------------------
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    description VARCHAR(150) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_roles_name UNIQUE (name),
    CONSTRAINT chk_roles_name CHECK (name IN ('ADMIN', 'ORGANIZER', 'PARTICIPANT'))
);

COMMENT ON TABLE roles IS 'Catálogo de roles utilizados para autorización dentro de la API.';
COMMENT ON COLUMN roles.id IS 'Identificador único del rol.';
COMMENT ON COLUMN roles.name IS 'Nombre técnico del rol: ADMIN, ORGANIZER o PARTICIPANT.';
COMMENT ON COLUMN roles.description IS 'Descripción funcional del rol.';
COMMENT ON COLUMN roles.created_at IS 'Fecha de creación del registro.';

-- --------------------------------------------------------------------------
-- 2. USERS
-- --------------------------------------------------------------------------
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    email VARCHAR(160) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_email_lowercase CHECK (email = LOWER(email)),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'BLOCKED'))
);

COMMENT ON TABLE users IS 'Usuarios del sistema. El bloqueo administrativo permanente se almacena en status; los bloqueos temporales de login se gestionan en Redis.';
COMMENT ON COLUMN users.id IS 'Identificador único del usuario.';
COMMENT ON COLUMN users.first_name IS 'Nombres del usuario.';
COMMENT ON COLUMN users.last_name IS 'Apellidos del usuario.';
COMMENT ON COLUMN users.email IS 'Correo normalizado en minúsculas y utilizado como credencial de acceso.';
COMMENT ON COLUMN users.password_hash IS 'Contraseña protegida mediante BCrypt. Nunca debe almacenarse en texto plano.';
COMMENT ON COLUMN users.status IS 'Estado administrativo de la cuenta: ACTIVE o BLOCKED.';
COMMENT ON COLUMN users.created_at IS 'Fecha de creación del usuario.';
COMMENT ON COLUMN users.updated_at IS 'Fecha de última modificación del usuario.';

CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- --------------------------------------------------------------------------
-- 3. USER_ROLES
-- Tabla intermedia para la relación muchos a muchos entre users y roles.
-- --------------------------------------------------------------------------
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT
);

COMMENT ON TABLE user_roles IS 'Tabla intermedia que asigna uno o varios roles a cada usuario.';
COMMENT ON COLUMN user_roles.user_id IS 'Usuario al que se asigna el rol.';
COMMENT ON COLUMN user_roles.role_id IS 'Rol asignado al usuario.';
COMMENT ON COLUMN user_roles.assigned_at IS 'Fecha en que se realizó la asignación.';

-- --------------------------------------------------------------------------
-- 4. CATEGORIES
-- --------------------------------------------------------------------------
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_categories_name_lower
    ON categories (LOWER(name));

COMMENT ON TABLE categories IS 'Categorías utilizadas para clasificar los eventos. La eliminación es lógica mediante active=false.';
COMMENT ON COLUMN categories.id IS 'Identificador único de la categoría.';
COMMENT ON COLUMN categories.name IS 'Nombre de la categoría. No se permiten duplicados sin considerar mayúsculas.';
COMMENT ON COLUMN categories.description IS 'Descripción de la categoría.';
COMMENT ON COLUMN categories.active IS 'Indica si la categoría puede utilizarse en nuevos eventos.';
COMMENT ON COLUMN categories.created_at IS 'Fecha de creación de la categoría.';
COMMENT ON COLUMN categories.updated_at IS 'Fecha de última modificación de la categoría.';

CREATE TRIGGER trg_categories_set_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- --------------------------------------------------------------------------
-- 5. EVENTS
-- --------------------------------------------------------------------------
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    description TEXT NOT NULL,
    modality VARCHAR(20) NOT NULL,
    location VARCHAR(200),
    virtual_url VARCHAR(500),
    capacity INTEGER NOT NULL,
    available_capacity INTEGER NOT NULL,
    registration_start_at TIMESTAMPTZ NOT NULL,
    registration_end_at TIMESTAMPTZ NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    organizer_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_events_organizer
        FOREIGN KEY (organizer_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_events_category
        FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT,
    CONSTRAINT chk_events_modality
        CHECK (modality IN ('PRESENTIAL', 'VIRTUAL', 'HYBRID')),
    CONSTRAINT chk_events_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'FINISHED', 'CANCELLED')),
    CONSTRAINT chk_events_capacity
        CHECK (capacity > 0),
    CONSTRAINT chk_events_available_capacity
        CHECK (available_capacity BETWEEN 0 AND capacity),
    CONSTRAINT chk_events_date_order
        CHECK (
            registration_start_at < registration_end_at
            AND registration_end_at <= start_at
            AND start_at < end_at
        ),
    CONSTRAINT chk_events_modality_data
        CHECK (
            (modality = 'PRESENTIAL' AND location IS NOT NULL AND virtual_url IS NULL)
            OR (modality = 'VIRTUAL' AND location IS NULL AND virtual_url IS NOT NULL)
            OR (modality = 'HYBRID' AND location IS NOT NULL AND virtual_url IS NOT NULL)
        )
);

COMMENT ON TABLE events IS 'Eventos académicos administrados por organizadores. Incluye cupos, modalidad, fechas, estado y eliminación lógica.';
COMMENT ON COLUMN events.id IS 'Identificador único del evento.';
COMMENT ON COLUMN events.title IS 'Título público del evento.';
COMMENT ON COLUMN events.description IS 'Descripción detallada del evento.';
COMMENT ON COLUMN events.modality IS 'Modalidad: PRESENTIAL, VIRTUAL o HYBRID.';
COMMENT ON COLUMN events.location IS 'Lugar físico requerido para eventos presenciales o híbridos.';
COMMENT ON COLUMN events.virtual_url IS 'Enlace de acceso requerido para eventos virtuales o híbridos.';
COMMENT ON COLUMN events.capacity IS 'Cupo total configurado para el evento.';
COMMENT ON COLUMN events.available_capacity IS 'Cupos todavía disponibles. Solo las inscripciones CONFIRMED consumen cupo.';
COMMENT ON COLUMN events.registration_start_at IS 'Inicio del periodo de inscripciones.';
COMMENT ON COLUMN events.registration_end_at IS 'Fin del periodo de inscripciones.';
COMMENT ON COLUMN events.start_at IS 'Fecha y hora de inicio del evento.';
COMMENT ON COLUMN events.end_at IS 'Fecha y hora de finalización del evento.';
COMMENT ON COLUMN events.status IS 'Estado del evento: DRAFT, PUBLISHED, FINISHED o CANCELLED.';
COMMENT ON COLUMN events.organizer_id IS 'Usuario propietario del evento.';
COMMENT ON COLUMN events.category_id IS 'Categoría a la que pertenece el evento.';
COMMENT ON COLUMN events.deleted IS 'Marca de eliminación lógica.';
COMMENT ON COLUMN events.version IS 'Versión utilizada para control de concurrencia optimista con JPA.';
COMMENT ON COLUMN events.created_at IS 'Fecha de creación del evento.';
COMMENT ON COLUMN events.updated_at IS 'Fecha de última modificación del evento.';

CREATE INDEX idx_events_status ON events(status);
CREATE INDEX idx_events_category ON events(category_id);
CREATE INDEX idx_events_organizer ON events(organizer_id);
CREATE INDEX idx_events_start_at ON events(start_at);
CREATE INDEX idx_events_deleted ON events(deleted);

CREATE TRIGGER trg_events_set_updated_at
BEFORE UPDATE ON events
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- --------------------------------------------------------------------------
-- 6. SESSIONS
-- --------------------------------------------------------------------------
CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    location VARCHAR(200),
    virtual_url VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sessions_event
        FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE RESTRICT,
    CONSTRAINT chk_sessions_date_order
        CHECK (start_at < end_at),
    CONSTRAINT uq_sessions_event_title_start
        UNIQUE (event_id, title, start_at)
);

COMMENT ON TABLE sessions IS 'Sesiones, charlas o bloques horarios pertenecientes a un evento.';
COMMENT ON COLUMN sessions.id IS 'Identificador único de la sesión.';
COMMENT ON COLUMN sessions.event_id IS 'Evento al que pertenece la sesión.';
COMMENT ON COLUMN sessions.title IS 'Título de la sesión.';
COMMENT ON COLUMN sessions.description IS 'Descripción de la sesión.';
COMMENT ON COLUMN sessions.start_at IS 'Fecha y hora de inicio de la sesión.';
COMMENT ON COLUMN sessions.end_at IS 'Fecha y hora de finalización de la sesión.';
COMMENT ON COLUMN sessions.location IS 'Lugar físico de la sesión cuando corresponda.';
COMMENT ON COLUMN sessions.virtual_url IS 'Enlace virtual de la sesión cuando corresponda.';
COMMENT ON COLUMN sessions.created_at IS 'Fecha de creación de la sesión.';
COMMENT ON COLUMN sessions.updated_at IS 'Fecha de última modificación de la sesión.';

CREATE INDEX idx_sessions_event ON sessions(event_id);
CREATE INDEX idx_sessions_start_at ON sessions(start_at);

CREATE TRIGGER trg_sessions_set_updated_at
BEFORE UPDATE ON sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- --------------------------------------------------------------------------
-- 7. REGISTRATIONS
-- --------------------------------------------------------------------------
CREATE TABLE registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_code UUID NOT NULL,
    event_id BIGINT NOT NULL,
    participant_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uq_registrations_code UNIQUE (registration_code),
    CONSTRAINT uq_registrations_event_participant UNIQUE (event_id, participant_id),
    CONSTRAINT fk_registrations_event
        FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE RESTRICT,
    CONSTRAINT fk_registrations_participant
        FOREIGN KEY (participant_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_registrations_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT chk_registrations_confirmed_at
        CHECK (status <> 'CONFIRMED' OR confirmed_at IS NOT NULL),
    CONSTRAINT chk_registrations_cancelled_at
        CHECK (status <> 'CANCELLED' OR cancelled_at IS NOT NULL)
);

COMMENT ON TABLE registrations IS 'Inscripciones de participantes en eventos. Solo puede existir una inscripción por participante y evento.';
COMMENT ON COLUMN registrations.id IS 'Identificador interno de la inscripción.';
COMMENT ON COLUMN registrations.registration_code IS 'Código UUID público utilizado en comprobantes.';
COMMENT ON COLUMN registrations.event_id IS 'Evento solicitado por el participante.';
COMMENT ON COLUMN registrations.participant_id IS 'Usuario participante propietario de la inscripción.';
COMMENT ON COLUMN registrations.status IS 'Estado: PENDING, CONFIRMED, REJECTED o CANCELLED.';
COMMENT ON COLUMN registrations.registered_at IS 'Fecha de creación de la solicitud.';
COMMENT ON COLUMN registrations.status_updated_at IS 'Fecha del último cambio de estado.';
COMMENT ON COLUMN registrations.confirmed_at IS 'Fecha de confirmación cuando el estado es CONFIRMED.';
COMMENT ON COLUMN registrations.cancelled_at IS 'Fecha de cancelación cuando el estado es CANCELLED.';
COMMENT ON COLUMN registrations.version IS 'Versión para control de concurrencia optimista con JPA.';

CREATE INDEX idx_registrations_event ON registrations(event_id);
CREATE INDEX idx_registrations_participant ON registrations(participant_id);
CREATE INDEX idx_registrations_status ON registrations(status);
CREATE INDEX idx_registrations_event_status ON registrations(event_id, status);


-- --------------------------------------------------------------------------
-- 9. REFRESH_TOKENS
-- Se utiliza PostgreSQL para revocación porque Redis queda reservado para
-- bloqueo temporal de login y rate limiting.
-- --------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_ip VARCHAR(45),
    replaced_by_token_id UUID,

    CONSTRAINT uq_refresh_tokens_token_id UNIQUE (token_id),
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_refresh_tokens_expiration
        CHECK (expires_at > created_at),
    CONSTRAINT chk_refresh_tokens_revocation
        CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

COMMENT ON TABLE refresh_tokens IS 'Refresh tokens persistidos mediante hash para permitir renovación, rotación, cierre de sesión y revocación del lado del servidor.';
COMMENT ON COLUMN refresh_tokens.id IS 'Identificador interno del refresh token.';
COMMENT ON COLUMN refresh_tokens.token_id IS 'Identificador UUID incluido como jti del token.';
COMMENT ON COLUMN refresh_tokens.user_id IS 'Usuario propietario del token.';
COMMENT ON COLUMN refresh_tokens.token_hash IS 'Hash del refresh token. No se almacena el token original.';
COMMENT ON COLUMN refresh_tokens.expires_at IS 'Fecha de expiración.';
COMMENT ON COLUMN refresh_tokens.revoked_at IS 'Fecha de revocación. Nulo mientras el token está vigente.';
COMMENT ON COLUMN refresh_tokens.created_at IS 'Fecha de emisión.';
COMMENT ON COLUMN refresh_tokens.created_by_ip IS 'IP desde la que se emitió el token.';
COMMENT ON COLUMN refresh_tokens.replaced_by_token_id IS 'Identificador del nuevo token emitido durante una rotación.';

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

-- --------------------------------------------------------------------------
-- 10. AUDIT_LOGS
-- --------------------------------------------------------------------------
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    action VARCHAR(60) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    resource_id BIGINT,
    previous_value JSONB,
    new_value JSONB,
    result VARCHAR(20) NOT NULL,
    ip_address VARCHAR(45),
    http_method VARCHAR(10),
    endpoint VARCHAR(255),
    correlation_id VARCHAR(36),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_actor
        FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_audit_logs_result
        CHECK (result IN ('SUCCESS', 'FAILED'))
);

COMMENT ON TABLE audit_logs IS 'Auditoría de operaciones críticas. No debe almacenar contraseñas, access tokens ni refresh tokens.';
COMMENT ON COLUMN audit_logs.id IS 'Identificador del registro de auditoría.';
COMMENT ON COLUMN audit_logs.actor_id IS 'Usuario autenticado que ejecutó la operación. Puede ser nulo.';
COMMENT ON COLUMN audit_logs.action IS 'Acción técnica realizada.';
COMMENT ON COLUMN audit_logs.resource_type IS 'Tipo de recurso afectado.';
COMMENT ON COLUMN audit_logs.resource_id IS 'Identificador del recurso afectado.';
COMMENT ON COLUMN audit_logs.previous_value IS 'Estado anterior serializado como JSON.';
COMMENT ON COLUMN audit_logs.new_value IS 'Estado nuevo serializado como JSON.';
COMMENT ON COLUMN audit_logs.result IS 'Resultado de la operación: SUCCESS o FAILED.';
COMMENT ON COLUMN audit_logs.ip_address IS 'Dirección IPv4 o IPv6 de origen.';
COMMENT ON COLUMN audit_logs.http_method IS 'Método HTTP utilizado.';
COMMENT ON COLUMN audit_logs.endpoint IS 'Ruta solicitada.';
COMMENT ON COLUMN audit_logs.correlation_id IS 'Identificador para relacionar auditoría y logs técnicos.';
COMMENT ON COLUMN audit_logs.created_at IS 'Fecha de la operación.';

CREATE INDEX idx_audit_logs_actor ON audit_logs(actor_id);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_resource ON audit_logs(resource_type, resource_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);

-- ============================================================================
-- DATOS INICIALES
-- ============================================================================

-- --------------------------------------------------------------------------
-- Roles
-- --------------------------------------------------------------------------
INSERT INTO roles (id, name, description) VALUES
    (1, 'ADMIN', 'Administra usuarios, roles, categorías, estados y reportes generales.'),
    (2, 'ORGANIZER', 'Gestiona únicamente sus eventos, sesiones e inscripciones.'),
    (3, 'PARTICIPANT', 'Consulta eventos y gestiona sus propias inscripciones.');

-- --------------------------------------------------------------------------
-- Usuarios
-- Contraseña común para demostración: Password123*
-- --------------------------------------------------------------------------
INSERT INTO users (
    id, first_name, last_name, email, password_hash, status, created_at, updated_at
) VALUES
    (1, 'Administrador', 'Académico', 'admin@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '120 days', CURRENT_TIMESTAMP - INTERVAL '120 days'),
    (2, 'María Fernanda', 'Cordero Vega', 'maria.cordero@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '110 days', CURRENT_TIMESTAMP - INTERVAL '15 days'),
    (3, 'José Andrés', 'Mora Sánchez', 'jose.mora@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '105 days', CURRENT_TIMESTAMP - INTERVAL '20 days'),
    (4, 'Ana Lucía', 'Torres Paredes', 'ana.torres@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '12 days'),
    (5, 'Carlos Eduardo', 'Vélez Ortiz', 'carlos.velez@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '90 days', CURRENT_TIMESTAMP - INTERVAL '90 days'),
    (6, 'Sofía Isabel', 'Pérez Molina', 'sofia.perez@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '88 days', CURRENT_TIMESTAMP - INTERVAL '88 days'),
    (7, 'Daniel Alejandro', 'López Cabrera', 'daniel.lopez@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '84 days', CURRENT_TIMESTAMP - INTERVAL '84 days'),
    (8, 'Valentina', 'Gómez Salazar', 'valentina.gomez@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '80 days', CURRENT_TIMESTAMP - INTERVAL '80 days'),
    (9, 'Mateo Sebastián', 'Ruiz Ochoa', 'mateo.ruiz@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '76 days', CURRENT_TIMESTAMP - INTERVAL '76 days'),
    (10, 'Camila Alejandra', 'Mendoza León', 'camila.mendoza@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '72 days', CURRENT_TIMESTAMP - INTERVAL '72 days'),
    (11, 'Diego Fernando', 'Narváez Peña', 'diego.narvaez@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '68 days', CURRENT_TIMESTAMP - INTERVAL '68 days'),
    (12, 'Paula Andrea', 'Castillo Jara', 'paula.castillo@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '64 days', CURRENT_TIMESTAMP - INTERVAL '64 days'),
    (13, 'Nicolás', 'Ortega Guamán', 'nicolas.ortega@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '60 days', CURRENT_TIMESTAMP - INTERVAL '60 days'),
    (14, 'Isabella', 'Romero Ávila', 'isabella.romero@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '56 days', CURRENT_TIMESTAMP - INTERVAL '56 days'),
    (15, 'Sebastián', 'Cárdenas Flores', 'sebastian.cardenas@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '52 days', CURRENT_TIMESTAMP - INTERVAL '52 days'),
    (16, 'Gabriela', 'Villacís Rojas', 'gabriela.villacis@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'ACTIVE', CURRENT_TIMESTAMP - INTERVAL '48 days', CURRENT_TIMESTAMP - INTERVAL '48 days'),
    (17, 'Andrés Felipe', 'Sarmiento Paz', 'andres.sarmiento@academic.test', '$2y$12$fUHCUNY8uzeZ9vObSXtQ9evcoxHcXWmzwGJcMZz93V6rQ4R9YGlAe', 'BLOCKED', CURRENT_TIMESTAMP - INTERVAL '44 days', CURRENT_TIMESTAMP - INTERVAL '2 days');

-- --------------------------------------------------------------------------
-- Asignación de roles
-- --------------------------------------------------------------------------
INSERT INTO user_roles (user_id, role_id, assigned_at) VALUES
    (1, 1, CURRENT_TIMESTAMP - INTERVAL '120 days'),

    (2, 2, CURRENT_TIMESTAMP - INTERVAL '100 days'),
    (2, 3, CURRENT_TIMESTAMP - INTERVAL '110 days'),
    (3, 2, CURRENT_TIMESTAMP - INTERVAL '95 days'),
    (3, 3, CURRENT_TIMESTAMP - INTERVAL '105 days'),
    (4, 2, CURRENT_TIMESTAMP - INTERVAL '90 days'),
    (4, 3, CURRENT_TIMESTAMP - INTERVAL '100 days'),

    (5, 3, CURRENT_TIMESTAMP - INTERVAL '90 days'),
    (6, 3, CURRENT_TIMESTAMP - INTERVAL '88 days'),
    (7, 3, CURRENT_TIMESTAMP - INTERVAL '84 days'),
    (8, 3, CURRENT_TIMESTAMP - INTERVAL '80 days'),
    (9, 3, CURRENT_TIMESTAMP - INTERVAL '76 days'),
    (10, 3, CURRENT_TIMESTAMP - INTERVAL '72 days'),
    (11, 3, CURRENT_TIMESTAMP - INTERVAL '68 days'),
    (12, 3, CURRENT_TIMESTAMP - INTERVAL '64 days'),
    (13, 3, CURRENT_TIMESTAMP - INTERVAL '60 days'),
    (14, 3, CURRENT_TIMESTAMP - INTERVAL '56 days'),
    (15, 3, CURRENT_TIMESTAMP - INTERVAL '52 days'),
    (16, 3, CURRENT_TIMESTAMP - INTERVAL '48 days'),
    (17, 3, CURRENT_TIMESTAMP - INTERVAL '44 days');

-- --------------------------------------------------------------------------
-- Categorías
-- --------------------------------------------------------------------------
INSERT INTO categories (id, name, description, active, created_at, updated_at) VALUES
    (1, 'Desarrollo de Software', 'Eventos relacionados con programación, arquitectura y buenas prácticas.', TRUE, CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '100 days'),
    (2, 'Inteligencia Artificial', 'Conferencias y talleres sobre IA, aprendizaje automático y datos.', TRUE, CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '100 days'),
    (3, 'Ciberseguridad', 'Seguridad de aplicaciones, redes, identidad y protección de datos.', TRUE, CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '100 days'),
    (4, 'Cloud y DevOps', 'Infraestructura, contenedores, automatización y despliegue.', TRUE, CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '100 days'),
    (5, 'Bases de Datos', 'Modelado, persistencia, SQL, NoSQL y optimización.', TRUE, CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '100 days'),
    (6, 'Diseño UX/UI', 'Experiencia de usuario, accesibilidad y diseño de interfaces.', TRUE, CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '100 days'),
    (7, 'Tecnologías Legadas', 'Categoría inactiva conservada para demostrar eliminación lógica.', FALSE, CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '10 days');

-- --------------------------------------------------------------------------
-- Eventos
-- Las fechas se calculan respecto al momento en que se ejecuta la migración.
-- --------------------------------------------------------------------------
INSERT INTO events (
    id, title, description, modality, location, virtual_url,
    capacity, available_capacity,
    registration_start_at, registration_end_at, start_at, end_at,
    status, organizer_id, category_id, deleted, version, created_at, updated_at
) VALUES
    (
        1,
        'Taller de seguridad con Spring Boot',
        'Construcción de una API REST con Spring Security, JWT, validación y autorización por roles.',
        'HYBRID',
        'Laboratorio de Computación 3',
        'https://meet.example.test/spring-security',
        40, 33,
        CURRENT_TIMESTAMP - INTERVAL '10 days',
        CURRENT_TIMESTAMP + INTERVAL '15 days',
        CURRENT_TIMESTAMP + INTERVAL '20 days',
        CURRENT_TIMESTAMP + INTERVAL '20 days 4 hours',
        'PUBLISHED', 2, 1, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '5 days'
    ),
    (
        2,
        'Congreso universitario de inteligencia artificial',
        'Ponencias sobre modelos generativos, visión artificial, ética y aplicaciones académicas de inteligencia artificial.',
        'PRESENTIAL',
        'Teatro Universitario',
        NULL,
        120, 112,
        CURRENT_TIMESTAMP - INTERVAL '20 days',
        CURRENT_TIMESTAMP + INTERVAL '25 days',
        CURRENT_TIMESTAMP + INTERVAL '30 days',
        CURRENT_TIMESTAMP + INTERVAL '31 days',
        'PUBLISHED', 3, 2, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '45 days', CURRENT_TIMESTAMP - INTERVAL '4 days'
    ),
    (
        3,
        'Aplicaciones web modernas con React',
        'Taller práctico sobre componentes, estado, consumo de API REST y organización de proyectos React.',
        'VIRTUAL',
        NULL,
        'https://meet.example.test/react-modern',
        35, 30,
        CURRENT_TIMESTAMP - INTERVAL '5 days',
        CURRENT_TIMESTAMP + INTERVAL '18 days',
        CURRENT_TIMESTAMP + INTERVAL '22 days',
        CURRENT_TIMESTAMP + INTERVAL '22 days 3 hours',
        'PUBLISHED', 4, 1, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '3 days'
    ),
    (
        4,
        'Arquitectura cloud para aplicaciones universitarias',
        'Diseño de una arquitectura desplegable con balanceo, servicios administrados y observabilidad.',
        'VIRTUAL',
        NULL,
        'https://meet.example.test/cloud-architecture',
        50, 50,
        CURRENT_TIMESTAMP + INTERVAL '5 days',
        CURRENT_TIMESTAMP + INTERVAL '35 days',
        CURRENT_TIMESTAMP + INTERVAL '40 days',
        CURRENT_TIMESTAMP + INTERVAL '40 days 3 hours',
        'DRAFT', 2, 4, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '1 day'
    ),
    (
        5,
        'Hackathon de soluciones web 2026',
        'Competencia por equipos para desarrollar una solución web funcional durante una jornada intensiva.',
        'PRESENTIAL',
        'Edificio de Laboratorios, piso 2',
        NULL,
        60, 54,
        CURRENT_TIMESTAMP - INTERVAL '15 days',
        CURRENT_TIMESTAMP + INTERVAL '40 days',
        CURRENT_TIMESTAMP + INTERVAL '45 days',
        CURRENT_TIMESTAMP + INTERVAL '46 days',
        'PUBLISHED', 3, 1, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '2 days'
    ),
    (
        6,
        'Seminario de ciberseguridad aplicada',
        'Seminario concluido sobre análisis de amenazas, autenticación y protección de servicios web.',
        'HYBRID',
        'Auditorio Principal',
        'https://meet.example.test/security-seminar',
        80, 75,
        CURRENT_TIMESTAMP - INTERVAL '80 days',
        CURRENT_TIMESTAMP - INTERVAL '45 days',
        CURRENT_TIMESTAMP - INTERVAL '40 days',
        CURRENT_TIMESTAMP - INTERVAL '39 days',
        'FINISHED', 4, 3, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '90 days', CURRENT_TIMESTAMP - INTERVAL '39 days'
    ),
    (
        7,
        'Taller de Git y GitHub colaborativo',
        'Evento cancelado utilizado para validar filtros y transiciones de estado.',
        'PRESENTIAL',
        'Laboratorio de Computación 1',
        NULL,
        50, 50,
        CURRENT_TIMESTAMP - INTERVAL '30 days',
        CURRENT_TIMESTAMP + INTERVAL '5 days',
        CURRENT_TIMESTAMP + INTERVAL '10 days',
        CURRENT_TIMESTAMP + INTERVAL '10 days 4 hours',
        'CANCELLED', 2, 4, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '2 days'
    ),
    (
        8,
        'Diseño de APIs REST con Java',
        'Práctica sobre recursos, endpoints, DTO, manejo de errores, persistencia y documentación OpenAPI.',
        'HYBRID',
        'Laboratorio de Computación 5',
        'https://meet.example.test/rest-java',
        45, 41,
        CURRENT_TIMESTAMP - INTERVAL '2 days',
        CURRENT_TIMESTAMP + INTERVAL '28 days',
        CURRENT_TIMESTAMP + INTERVAL '32 days',
        CURRENT_TIMESTAMP + INTERVAL '32 days 5 hours',
        'PUBLISHED', 2, 1, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP - INTERVAL '1 day'
    ),
    (
        9,
        'PostgreSQL para aplicaciones empresariales',
        'Modelado relacional, restricciones, índices, transacciones y optimización de consultas.',
        'PRESENTIAL',
        'Laboratorio de Bases de Datos',
        NULL,
        30, 30,
        CURRENT_TIMESTAMP + INTERVAL '10 days',
        CURRENT_TIMESTAMP + INTERVAL '50 days',
        CURRENT_TIMESTAMP + INTERVAL '55 days',
        CURRENT_TIMESTAMP + INTERVAL '55 days 4 hours',
        'DRAFT', 3, 5, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '1 day'
    ),
    (
        10,
        'Diseño UX para plataformas académicas',
        'Aplicación de heurísticas, accesibilidad y diseño centrado en el usuario en sistemas universitarios.',
        'VIRTUAL',
        NULL,
        'https://meet.example.test/ux-academic',
        30, 27,
        CURRENT_TIMESTAMP - INTERVAL '7 days',
        CURRENT_TIMESTAMP + INTERVAL '12 days',
        CURRENT_TIMESTAMP + INTERVAL '16 days',
        CURRENT_TIMESTAMP + INTERVAL '16 days 3 hours',
        'PUBLISHED', 4, 6, FALSE, 0,
        CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP - INTERVAL '2 days'
    ),
    (
        11,
        'Introducción a sistemas monolíticos legados',
        'Registro eliminado lógicamente para demostrar que no debe aparecer en los listados públicos.',
        'VIRTUAL',
        NULL,
        'https://meet.example.test/legacy-systems',
        25, 25,
        CURRENT_TIMESTAMP - INTERVAL '20 days',
        CURRENT_TIMESTAMP + INTERVAL '8 days',
        CURRENT_TIMESTAMP + INTERVAL '12 days',
        CURRENT_TIMESTAMP + INTERVAL '12 days 2 hours',
        'DRAFT', 3, 7, TRUE, 0,
        CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '3 days'
    );

-- --------------------------------------------------------------------------
-- Sesiones
-- --------------------------------------------------------------------------
INSERT INTO sessions (
    id, event_id, title, description, start_at, end_at, location, virtual_url, created_at, updated_at
) VALUES
    (1, 1, 'Configuración de Spring Security', 'Filtros, SecurityFilterChain y protección de endpoints.', CURRENT_TIMESTAMP + INTERVAL '20 days', CURRENT_TIMESTAMP + INTERVAL '20 days 1 hour 30 minutes', 'Laboratorio de Computación 3', 'https://meet.example.test/spring-security/session-1', CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '5 days'),
    (2, 1, 'JWT y autorización por recursos', 'Access token, refresh token, roles y propiedad de recursos.', CURRENT_TIMESTAMP + INTERVAL '20 days 1 hour 45 minutes', CURRENT_TIMESTAMP + INTERVAL '20 days 4 hours', 'Laboratorio de Computación 3', 'https://meet.example.test/spring-security/session-2', CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '5 days'),

    (3, 2, 'Modelos generativos en educación', 'Aplicaciones, riesgos y criterios éticos.', CURRENT_TIMESTAMP + INTERVAL '30 days', CURRENT_TIMESTAMP + INTERVAL '30 days 2 hours', 'Teatro Universitario', NULL, CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '4 days'),
    (4, 2, 'Visión artificial aplicada', 'Casos académicos de clasificación y reconocimiento.', CURRENT_TIMESTAMP + INTERVAL '30 days 3 hours', CURRENT_TIMESTAMP + INTERVAL '30 days 5 hours', 'Teatro Universitario', NULL, CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '4 days'),
    (5, 2, 'Taller de prototipado con IA', 'Construcción de un prototipo funcional.', CURRENT_TIMESTAMP + INTERVAL '31 days', CURRENT_TIMESTAMP + INTERVAL '31 days 4 hours', 'Laboratorio de Inteligencia Artificial', NULL, CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '4 days'),

    (6, 3, 'Componentes y propiedades', 'Organización de componentes reutilizables.', CURRENT_TIMESTAMP + INTERVAL '22 days', CURRENT_TIMESTAMP + INTERVAL '22 days 1 hour 20 minutes', NULL, 'https://meet.example.test/react-modern/session-1', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP - INTERVAL '3 days'),
    (7, 3, 'Consumo de API REST', 'Peticiones HTTP, estados de carga y manejo de errores.', CURRENT_TIMESTAMP + INTERVAL '22 days 1 hour 30 minutes', CURRENT_TIMESTAMP + INTERVAL '22 days 3 hours', NULL, 'https://meet.example.test/react-modern/session-2', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP - INTERVAL '3 days'),

    (8, 4, 'Arquitectura base', 'Diseño de componentes de infraestructura.', CURRENT_TIMESTAMP + INTERVAL '40 days', CURRENT_TIMESTAMP + INTERVAL '40 days 1 hour 20 minutes', NULL, 'https://meet.example.test/cloud-architecture/session-1', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
    (9, 4, 'Despliegue y observabilidad', 'Servicios administrados, logs y health checks.', CURRENT_TIMESTAMP + INTERVAL '40 days 1 hour 30 minutes', CURRENT_TIMESTAMP + INTERVAL '40 days 3 hours', NULL, 'https://meet.example.test/cloud-architecture/session-2', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),

    (10, 5, 'Apertura y presentación del reto', 'Explicación de reglas y conformación de equipos.', CURRENT_TIMESTAMP + INTERVAL '45 days', CURRENT_TIMESTAMP + INTERVAL '45 days 1 hour', 'Edificio de Laboratorios, piso 2', NULL, CURRENT_TIMESTAMP - INTERVAL '22 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
    (11, 5, 'Desarrollo de soluciones', 'Jornada principal de implementación.', CURRENT_TIMESTAMP + INTERVAL '45 days 1 hour', CURRENT_TIMESTAMP + INTERVAL '45 days 12 hours', 'Edificio de Laboratorios, piso 2', NULL, CURRENT_TIMESTAMP - INTERVAL '22 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
    (12, 5, 'Presentación y premiación', 'Sustentación de proyectos y cierre.', CURRENT_TIMESTAMP + INTERVAL '46 days', CURRENT_TIMESTAMP + INTERVAL '46 days 4 hours', 'Auditorio Principal', NULL, CURRENT_TIMESTAMP - INTERVAL '22 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),

    (13, 6, 'Amenazas en aplicaciones web', 'Sesión histórica de un evento finalizado.', CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '40 days' + INTERVAL '3 hours', 'Auditorio Principal', 'https://meet.example.test/security-seminar/session-1', CURRENT_TIMESTAMP - INTERVAL '85 days', CURRENT_TIMESTAMP - INTERVAL '39 days'),
    (14, 6, 'Autenticación y control de acceso', 'Sesión histórica de un evento finalizado.', CURRENT_TIMESTAMP - INTERVAL '39 days 7 hours', CURRENT_TIMESTAMP - INTERVAL '39 days 4 hours', 'Auditorio Principal', 'https://meet.example.test/security-seminar/session-2', CURRENT_TIMESTAMP - INTERVAL '85 days', CURRENT_TIMESTAMP - INTERVAL '39 days'),

    (15, 7, 'Flujo colaborativo con Pull Requests', 'Sesión perteneciente a un evento cancelado.', CURRENT_TIMESTAMP + INTERVAL '10 days', CURRENT_TIMESTAMP + INTERVAL '10 days 4 hours', 'Laboratorio de Computación 1', NULL, CURRENT_TIMESTAMP - INTERVAL '35 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),

    (16, 8, 'Diseño de recursos y endpoints', 'Recursos, verbos HTTP, códigos y rutas.', CURRENT_TIMESTAMP + INTERVAL '32 days', CURRENT_TIMESTAMP + INTERVAL '32 days 2 hours', 'Laboratorio de Computación 5', 'https://meet.example.test/rest-java/session-1', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
    (17, 8, 'DTO, persistencia y errores', 'DTO, JPA, transacciones y excepciones centralizadas.', CURRENT_TIMESTAMP + INTERVAL '32 days 2 hours 15 minutes', CURRENT_TIMESTAMP + INTERVAL '32 days 5 hours', 'Laboratorio de Computación 5', 'https://meet.example.test/rest-java/session-2', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),

    (18, 9, 'Modelado y restricciones', 'Diseño de tablas y reglas de integridad.', CURRENT_TIMESTAMP + INTERVAL '55 days', CURRENT_TIMESTAMP + INTERVAL '55 days 2 hours', 'Laboratorio de Bases de Datos', NULL, CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
    (19, 9, 'Índices y transacciones', 'Optimización y consistencia de datos.', CURRENT_TIMESTAMP + INTERVAL '55 days 2 hours 15 minutes', CURRENT_TIMESTAMP + INTERVAL '55 days 4 hours', 'Laboratorio de Bases de Datos', NULL, CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),

    (20, 10, 'Evaluación heurística', 'Aplicación de heurísticas de usabilidad.', CURRENT_TIMESTAMP + INTERVAL '16 days', CURRENT_TIMESTAMP + INTERVAL '16 days 1 hour 20 minutes', NULL, 'https://meet.example.test/ux-academic/session-1', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
    (21, 10, 'Accesibilidad y rediseño', 'Propuesta de mejoras para plataformas académicas.', CURRENT_TIMESTAMP + INTERVAL '16 days 1 hour 30 minutes', CURRENT_TIMESTAMP + INTERVAL '16 days 3 hours', NULL, 'https://meet.example.test/ux-academic/session-2', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP - INTERVAL '2 days');

-- --------------------------------------------------------------------------
-- Inscripciones
-- Las cantidades CONFIRMED coinciden con available_capacity de cada evento.
-- --------------------------------------------------------------------------
INSERT INTO registrations (
    id, registration_code, event_id, participant_id, status,
    registered_at, status_updated_at, confirmed_at, cancelled_at, version
) VALUES
    -- Evento 1: 7 confirmadas y 1 pendiente
    (1, '00000000-0000-4000-8000-000000000001', 1, 5, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP - INTERVAL '7 days', NULL, 0),
    (2, '00000000-0000-4000-8000-000000000002', 1, 6, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP - INTERVAL '7 days', NULL, 0),
    (3, '00000000-0000-4000-8000-000000000003', 1, 7, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '6 days', NULL, 0),
    (4, '00000000-0000-4000-8000-000000000004', 1, 8, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '6 days', NULL, 0),
    (5, '00000000-0000-4000-8000-000000000005', 1, 9, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '5 days', NULL, 0),
    (6, '00000000-0000-4000-8000-000000000006', 1, 10, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '5 days', NULL, 0),
    (7, '00000000-0000-4000-8000-000000000007', 1, 11, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '4 days', NULL, 0),
    (8, '00000000-0000-4000-8000-000000000008', 1, 12, 'PENDING', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '2 days', NULL, NULL, 0),

    -- Evento 2: 8 confirmadas, 1 pendiente y 1 rechazada
    (9, '00000000-0000-4000-8000-000000000009', 2, 5, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP - INTERVAL '17 days', CURRENT_TIMESTAMP - INTERVAL '17 days', NULL, 0),
    (10, '00000000-0000-4000-8000-000000000010', 2, 6, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '17 days', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP - INTERVAL '16 days', NULL, 0),
    (11, '00000000-0000-4000-8000-000000000011', 2, 8, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '15 days', NULL, 0),
    (12, '00000000-0000-4000-8000-000000000012', 2, 9, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP - INTERVAL '14 days', NULL, 0),
    (13, '00000000-0000-4000-8000-000000000013', 2, 10, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP - INTERVAL '13 days', CURRENT_TIMESTAMP - INTERVAL '13 days', NULL, 0),
    (14, '00000000-0000-4000-8000-000000000014', 2, 11, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '13 days', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '12 days', NULL, 0),
    (15, '00000000-0000-4000-8000-000000000015', 2, 12, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP - INTERVAL '11 days', NULL, 0),
    (16, '00000000-0000-4000-8000-000000000016', 2, 13, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '10 days', NULL, 0),
    (17, '00000000-0000-4000-8000-000000000017', 2, 14, 'PENDING', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '3 days', NULL, NULL, 0),
    (18, '00000000-0000-4000-8000-000000000018', 2, 15, 'REJECTED', CURRENT_TIMESTAMP - INTERVAL '9 days', CURRENT_TIMESTAMP - INTERVAL '8 days', NULL, NULL, 0),

    -- Evento 3: 5 confirmadas y 1 cancelada
    (19, '00000000-0000-4000-8000-000000000019', 3, 7, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '3 days', NULL, 0),
    (20, '00000000-0000-4000-8000-000000000020', 3, 8, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '3 days', NULL, 0),
    (21, '00000000-0000-4000-8000-000000000021', 3, 9, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '2 days', NULL, 0),
    (22, '00000000-0000-4000-8000-000000000022', 3, 10, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '2 days', NULL, 0),
    (23, '00000000-0000-4000-8000-000000000023', 3, 11, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', NULL, 0),
    (24, '00000000-0000-4000-8000-000000000024', 3, 12, 'CANCELLED', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '1 day', NULL, CURRENT_TIMESTAMP - INTERVAL '1 day', 0),

    -- Evento 5: 6 confirmadas
    (25, '00000000-0000-4000-8000-000000000025', 5, 5, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP - INTERVAL '11 days', NULL, 0),
    (26, '00000000-0000-4000-8000-000000000026', 5, 9, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '10 days', NULL, 0),
    (27, '00000000-0000-4000-8000-000000000027', 5, 13, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '9 days', CURRENT_TIMESTAMP - INTERVAL '9 days', NULL, 0),
    (28, '00000000-0000-4000-8000-000000000028', 5, 14, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '9 days', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '8 days', NULL, 0),
    (29, '00000000-0000-4000-8000-000000000029', 5, 15, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP - INTERVAL '7 days', NULL, 0),
    (30, '00000000-0000-4000-8000-000000000030', 5, 16, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '6 days', NULL, 0),

    -- Evento 6 finalizado: 5 confirmadas
    (31, '00000000-0000-4000-8000-000000000031', 6, 5, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '65 days', CURRENT_TIMESTAMP - INTERVAL '64 days', CURRENT_TIMESTAMP - INTERVAL '64 days', NULL, 0),
    (32, '00000000-0000-4000-8000-000000000032', 6, 6, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '64 days', CURRENT_TIMESTAMP - INTERVAL '63 days', CURRENT_TIMESTAMP - INTERVAL '63 days', NULL, 0),
    (33, '00000000-0000-4000-8000-000000000033', 6, 7, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '63 days', CURRENT_TIMESTAMP - INTERVAL '62 days', CURRENT_TIMESTAMP - INTERVAL '62 days', NULL, 0),
    (34, '00000000-0000-4000-8000-000000000034', 6, 8, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '62 days', CURRENT_TIMESTAMP - INTERVAL '61 days', CURRENT_TIMESTAMP - INTERVAL '61 days', NULL, 0),
    (35, '00000000-0000-4000-8000-000000000035', 6, 9, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '61 days', CURRENT_TIMESTAMP - INTERVAL '60 days', CURRENT_TIMESTAMP - INTERVAL '60 days', NULL, 0),

    -- Evento 7 cancelado: inscripciones canceladas y cupos liberados
    (36, '00000000-0000-4000-8000-000000000036', 7, 10, 'CANCELLED', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '2 days', NULL, CURRENT_TIMESTAMP - INTERVAL '2 days', 0),
    (37, '00000000-0000-4000-8000-000000000037', 7, 11, 'CANCELLED', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP - INTERVAL '2 days', NULL, CURRENT_TIMESTAMP - INTERVAL '2 days', 0),

    -- Evento 8: 4 confirmadas y 1 pendiente
    (38, '00000000-0000-4000-8000-000000000038', 8, 6, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', NULL, 0),
    (39, '00000000-0000-4000-8000-000000000039', 8, 10, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', NULL, 0),
    (40, '00000000-0000-4000-8000-000000000040', 8, 14, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '12 hours', CURRENT_TIMESTAMP - INTERVAL '12 hours', NULL, 0),
    (41, '00000000-0000-4000-8000-000000000041', 8, 16, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '10 hours', CURRENT_TIMESTAMP - INTERVAL '10 hours', NULL, 0),
    (42, '00000000-0000-4000-8000-000000000042', 8, 13, 'PENDING', CURRENT_TIMESTAMP - INTERVAL '6 hours', CURRENT_TIMESTAMP - INTERVAL '6 hours', NULL, NULL, 0),

    -- Evento 10: 3 confirmadas
    (43, '00000000-0000-4000-8000-000000000043', 10, 7, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '4 days', NULL, 0),
    (44, '00000000-0000-4000-8000-000000000044', 10, 12, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '3 days', NULL, 0),
    (45, '00000000-0000-4000-8000-000000000045', 10, 15, 'CONFIRMED', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '2 days', NULL, 0);

s
-- --------------------------------------------------------------------------
-- Auditoría de ejemplo
-- --------------------------------------------------------------------------
INSERT INTO audit_logs (
    id, actor_id, action, resource_type, resource_id,
    previous_value, new_value, result, ip_address,
    http_method, endpoint, correlation_id, created_at
) VALUES
    (
        1, 1, 'USER_ROLES_UPDATED', 'USER', 2,
        '{"roles":["PARTICIPANT"]}'::jsonb,
        '{"roles":["PARTICIPANT","ORGANIZER"]}'::jsonb,
        'SUCCESS', '192.168.10.20', 'PUT', '/api/users/2/roles',
        '11111111-1111-4111-8111-111111111111', CURRENT_TIMESTAMP - INTERVAL '100 days'
    ),
    (
        2, 2, 'LOGIN_SUCCESS', 'USER', 2,
        NULL,
        '{"email":"maria.cordero@academic.test"}'::jsonb,
        'SUCCESS', '192.168.10.25', 'POST', '/api/auth/login',
        '22222222-2222-4222-8222-222222222222', CURRENT_TIMESTAMP - INTERVAL '2 days'
    ),
    (
        3, NULL, 'LOGIN_FAILED', 'USER', NULL,
        NULL,
        '{"email":"usuario.inexistente@academic.test"}'::jsonb,
        'FAILED', '192.168.10.30', 'POST', '/api/auth/login',
        '33333333-3333-4333-8333-333333333333', CURRENT_TIMESTAMP - INTERVAL '1 day'
    ),
    (
        4, 2, 'REGISTRATION_STATUS_CHANGED', 'REGISTRATION', 1,
        '{"status":"PENDING"}'::jsonb,
        '{"status":"CONFIRMED"}'::jsonb,
        'SUCCESS', '192.168.10.25', 'PATCH', '/api/registrations/1/status',
        '44444444-4444-4444-8444-444444444444', CURRENT_TIMESTAMP - INTERVAL '7 days'
    ),
    (
        5, 1, 'USER_STATUS_CHANGED', 'USER', 17,
        '{"status":"ACTIVE"}'::jsonb,
        '{"status":"BLOCKED"}'::jsonb,
        'SUCCESS', '192.168.10.20', 'PATCH', '/api/users/17/status',
        '55555555-5555-4555-8555-555555555555', CURRENT_TIMESTAMP - INTERVAL '2 days'
    );

-- --------------------------------------------------------------------------
-- Ajuste de las secuencias después de insertar identificadores explícitos.
-- --------------------------------------------------------------------------
SELECT setval(pg_get_serial_sequence('roles', 'id'), COALESCE(MAX(id), 1), TRUE) FROM roles;
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1), TRUE) FROM users;
SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE(MAX(id), 1), TRUE) FROM categories;
SELECT setval(pg_get_serial_sequence('events', 'id'), COALESCE(MAX(id), 1), TRUE) FROM events;
SELECT setval(pg_get_serial_sequence('sessions', 'id'), COALESCE(MAX(id), 1), TRUE) FROM sessions;
SELECT setval(pg_get_serial_sequence('registrations', 'id'), COALESCE(MAX(id), 1), TRUE) FROM registrations;

SELECT setval(pg_get_serial_sequence('audit_logs', 'id'), COALESCE(MAX(id), 1), TRUE) FROM audit_logs;

-- ============================================================================
-- Consultas de verificación sugeridas
-- ============================================================================
-- SELECT * FROM roles ORDER BY id;
-- SELECT id, first_name, last_name, email, status FROM users ORDER BY id;
-- SELECT u.id, u.email, ARRAY_AGG(r.name ORDER BY r.name) AS roles
-- FROM users u
-- JOIN user_roles ur ON ur.user_id = u.id
-- JOIN roles r ON r.id = ur.role_id
-- GROUP BY u.id, u.email
-- ORDER BY u.id;
-- SELECT id, title, modality, capacity, available_capacity, status FROM events ORDER BY id;
-- SELECT * FROM sessions WHERE event_id = 1 ORDER BY start_at;
-- SELECT * FROM registrations WHERE event_id = 1 ORDER BY id;
-- SELECT * FROM audit_logs ORDER BY created_at DESC;
